application: ods_biz
checkpoint:
  checkpointInterval: 60000
  minPauseBetweenCheckpoints: 60000
  checkpointTimeout: 120000
maintenance:
  restartUrl: http://192.168.100.147:30001/job/restart
redis:
  host: 192.168.15.67
  port: 6379
  password: 123456
monitor:
  delete:
    key: 1f39e3a2-f60f-4a2b-8ca7-85bdf38dc439
    messageTemplate: '{"msgtype":"markdown","markdown":{"content":"表数据物理删除：\n> application: %s\n> 目标库: %s\n> 目标表: %s\n> 删除数据: %s"}}'
  ddl:
    key: a10b6ece-1a00-4cc0-a07b-418ef3xa5bae
    messageTemplate: '{"msgtype":"markdown","markdown":{"content":"**NO.**：%s\n**application id**：%s\n**job id**：%s\n**目标库**：%s\n**目标表**：%s\n**sourceOffset**：%s\n**ddl**：%s\n**arctic ddl**：%s"}}'
  ddlSync:
    key: b50b27e0-b4c0-46ab-b93f-042d4627aace
    messageTemplate: '{"msgtype":"markdown","markdown":{"content":"**application**：%s\n**目标库**：%s\n**目标表**：%s\n**ddl**：%s\n**同步结果**：%s"}}'
globalTimeZone: +08:00
hdfs:
  warehouse: hdfs://192.168.100.142:8020/user/hive/warehouse/
  uri: thrift://192.168.100.147:9083
  cacheDir: hdfs://192.168.100.142:8020/data/cache/ods_dev/
datasources:
  creditlimit:
    host: 192.168.15.53
    port: 3306
    username: root
    password: 123456
    details:
      credit_limit_00_db:
        # 1、数据库整个表全部生成；2、只生成指定的表；3、除了指定的表，全部生成
        # 无主键表：covid_test_users、izidata_test_collection、bnc、buyback
        type: 2
        sharding:
          dbNameSource: credit_limit_([0-9][0-9])_db
          dbNameTarget: credit_limit_db
          tables:
            t_card_credit_limit: t_card_credit_limit_[0-9]
  business:
    host: 192.168.15.28
    port: 3306
    username: root
    password: 123456
    details:
      cash_loan:
        # 1、数据库整个表全部生成；2、只生成指定的表；3、除了指定的表，全部生成
        type: 2
        tables:
          - bank_info
          - user