env: TEST
application: ods_business_test
kafkaBootstrapServers: snn:9092
sinkType: ICEBERGE
parallelism:
  execution: 1
  write: 1
checkpoint:
  checkpointInterval: 180000
  minPauseBetweenCheckpoints: 180000
  checkpointTimeout: 300000
redis:
  host: 192.168.10.1
  port: 6379
  password: 123456
proxy:
  host: 192.168.129.9
  port: 3128
monitor:
  delete:
    key: 07a49203-40ce-41d7-a341-535e72a6f67e
    messageTemplate: '{"msgtype":"markdown","markdown":{"content":"表数据物理删除：\n> application: %s\n> 目标库: %s\n> 目标表: %s\n> 删除数据: %s\n\n<@Collin>"}}'
  ddl:
    key: d17783a8-88df-44b8-a673-ed6ac9891239
    messageTemplate: '{"msgtype":"markdown","markdown":{"content":"**NO.**：%s\n**application id**：%s\n**job id**：%s\n**目标库**：%s\n**目标表**：%s\n**sourceOffset**：%s\n**ddl**：%s\n**arctic ddl**：%s\n<@Collin>"}}'
targetTimeZone: +07:00
hdfs:
  warehouse: hdfs://nameservice1/user/hive/warehouse/
  uri: thrift://nn:9083,thrift://snn:9083
  cacheDir: hdfs://nameservice1/data/cache/ods/
datasources:
  business:
    host: 192.168.8.1
    port: 3306
    username: flink_ro
    password: 123456
    timeZone: +07:00
    startServerId: 2101
    details:
      order_db:
        # 1、数据库整个表全部生成；2、只生成指定的表；3、除了指定的表，全部生成
        # 无主键表：covid_test_users、izidata_test_collection、bnc、buyback
        type: 2
        excludeDeleteTables:
          - device_installed_app
        tables:
          - urge_settle_order
      risk_db:
        # 1、数据库整个表全部生成；2、只生成指定的表；3、除了指定的表，全部生成
        type: 2
        tables:
          - lepin_inter_risk_rule